[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  # Configure secrets scanning to omit specific keys that cause false positives
  SECRETS_SCAN_OMIT_KEYS = "PORT,NODE_ENV"


